DROP TABLE IF EXISTS users,items,bookings,request,comments;
CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,

    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

-- CREATE TABLE items
-- (
--     id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     name        VARCHAR(255)                            NOT NULL,
--     description VARCHAR(512)                            NOT NULL,
--     available   BOOLEAN                                 NOT NULL,
--     owner_id    BIGINT                                  NOT NULL,
--     request_id  BIGINT                                  NOT NULL,
--
--     CONSTRAINT pk_item PRIMARY KEY (id)
-- );
create table items
(
    id          bigint generated by default as identity (maxvalue 2147483647)
        constraint items_pk
            primary key,
    name        varchar(255) not null,
    description varchar(512) not null,
    available   boolean      not null,
    owner_id    bigint       not null
        constraint items_users_id_fk
            references users,
    request_id  bigint
);

CREATE TABLE bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    booker_id  BIGINT                                  NOT NULL,
    status     BIGINT                                  NOT NULL,

    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    requester_id BIGINT                                  NOT NULL,

    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(512)                            NOT NULL,
    item_id   BIGINT                                  NOT NULL,
    author_id BIGINT                                  NOT NULL,

    CONSTRAINT pk_comment PRIMARY KEY (id)
);


