DROP TABLE IF EXISTS users,items,bookings,request,comments;
CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(100)                            NOT NULL,
    email VARCHAR(100)                            NOT NULL,

    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table items
(
    id          bigint generated by default as identity (maxvalue 2147483647)
        constraint items_pk
            primary key,
    name        varchar(100) not null,
    description varchar(512) not null,
    available   boolean      not null,
    owner_id    bigint       not null
        constraint items_users_id_fk
            references users,
    request_id  bigint
);

CREATE TABLE bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item       BIGINT                                  NOT NULL
        constraint bookings_items_id_fk
            references items,
    booker     BIGINT                                  NOT NULL
        constraint bookings_users_id_fk
            references users,
    booker_id  BIGINT                                  NOT NULL,

    status     BIGINT                                  NOT NULL,

    CONSTRAINT pk_booking PRIMARY KEY (id)
);


CREATE TABLE request
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    requester   BIGINT                                  NOT NULL
        constraint request_users_id_fk
            references users,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(512)                            NOT NULL,
    item_id   BIGINT                                  NOT NULL
        constraint comments_items_id_fk
            references items,
    author_id BIGINT                                  NOT NULL
        constraint comments_users_id_fk
            references users,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    CONSTRAINT pk_comment PRIMARY KEY (id)
);


